### ISSUE TITLE
HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by benjaminsigrist** [EsriDE/ArcGIS-Sentinel2-Download-Tools#1] opened 2018-08-16 08:01 UTC
Dear EsriDE

When I try to run a search, I get the following error message:

Start Time: Thu Aug 16 09:57:51 2018
Running script Search...
https://scihub.copernicus.eu/dhus/search?format=xml&sortedby=beginposition&order=desc&rows=100&q=(producttype:S2MSI2Ap+OR+producttype:S2MSI2A)+AND+beginPosition:[2018-01-01T00:00:00Z+TO+NOW]+AND+footprint:%22Intersects(POLYGON((7.922218+46.226793,7.922218+46.562661,8.512636+46.562661,8.512636+46.226793,7.922218+46.226793)))%22+AND+cloudCoverPercentage:[0+TO+80]&start=
Products found: 61
New finds: 61, already existent in local catalog: 0
Fetching metadata, tile preview(s) for...
...new find 1/61 (2018-03-26 10:30:21),
  tile 1/1 (32TMS)
...new find 2/61 (2018-02-06 10:22:09),

Traceback (most recent call last):
  File "<string>", line 243, in execute
  File "C:\Benja\UZH\Master_Thesis\Tools\Sentinel2Tools\ArcGIS-Sentinel2-Download-Tools-master\lib\sensub.py", line 127, in prodTiles
    info = json.load(urllib2.urlopen(url))
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

Failed to execute (Search).

A couple months back I managed to execute the search without any issues, any ideas what went wrong? Help is very much appreciated.

Ben

Ben

**Comment by esride-cgo** [comment] 2018-08-17 00:06
Thank you for indicating this!
The cause is: AWS disabled the public access of the L1C bucket on [7th of August 2018](https://forum.sentinel-hub.com/t/how-to-access-s-2-meta-data-in-aws-after-bucket-goes-to-requester-pays/328). Since so far this L1C bucket was used for some tasks, e.g. for retrieving the previews for L2A products that are dated before 2018-03-26, some code lines have to be fixed to cut out any AWS access attempts. This will be done within the next few days. (Until then, you can restrict the search to L2A products that are dated from 2018-03-26 onwards.)

**Comment by esride-cgo** [comment] 2018-08-17 18:35
The AWS access is now thrown out of the code, whereby this issue should be fixed now.
@benjaminsigrist : Please let me know whether this issue can be closed.

**Comment by benjaminsigrist** [comment] 2018-08-17 19:04
Thanks for keeping me posted. I downloaded the tools again, now the search
throws an error in every field of the tool: [image: Close Window] <#>
*ERROR *Traceback (most recent call last): File "", line 98, in
updateParameters KeyError: 'DHUSALT'

2018-08-17 20:35 GMT+02:00 esride-cgo <notifications@github.com>:

**Comment by esride-cgo** [comment] 2018-08-17 20:58
@benjaminsigrist Did you mean to post a screenshot? Your post doesn't show the image... anyway, I think your problem now is that ArcMap is in some kind of confused state (related to some module loading or instantiation artefacts, or so). I likewise faced this broken tool state occasionally in the past (when just having replaced the tool files), where then I had to restart ArcMap to get well again. So, can you restart ArcMap and try the tool again?

**Comment by benjaminsigrist** [comment] 2018-08-17 21:21
Oh boy, of course that would have been a smart move. Now it works like a
charm, thanks a lot for your efforts!

2018-08-17 22:58 GMT+02:00 esride-cgo <notifications@github.com>:

**Closed as completed** 2018-08-24 16:51 UTC
Labels: bug
